folders:
  pickle: info/pickle/
  ref_csv: info/ref_csv/
  csv: info/csv/
pickles:
  accounts: accounts.pkl
  movement_types: movement_types.pkl
raw_data_csv: raw_data.csv
acc_init: accounts_init.csv

eq_acc_id: 0
